# Generated by Django 3.2.4 on 2021-06-24 20:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('About', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url1', models.TextField()),
                ('image_url2', models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True)),
                ('image_url3', models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True)),
                ('image_url4', models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True)),
                ('image_url5', models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True)),
                ('text_para', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='Member_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Add new category')),
            ],
            options={
                'verbose_name_plural': 'Member Type',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('sub_text', models.TextField(blank=True, null=True)),
                ('link', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Papers_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Add new category')),
            ],
            options={
                'verbose_name_plural': 'Publication Category',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_Url', models.TextField()),
                ('info', ckeditor.fields.RichTextField()),
                ('publication_details', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Research',
            },
        ),
        migrations.CreateModel(
            name='Software_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tag Name')),
                ('color', models.CharField(max_length=10, verbose_name='Add color of the tag')),
            ],
            options={
                'verbose_name_plural': 'Software Tags',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageUrl', models.TextField(help_text='<p style="color:darkgreen">*<b>IMPORTANT </b> Square Dimensions Only*</p>')),
                ('designation', models.CharField(max_length=100)),
                ('about', ckeditor.fields.RichTextField()),
                ('email', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('member_type', models.ManyToManyField(blank=True, to='sengupta_lab.Member_Type')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('github_link', models.CharField(max_length=250)),
                ('tags', models.ManyToManyField(blank=True, to='sengupta_lab.Software_Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Paper Title')),
                ('imageUrl', models.TextField(help_text='<p style="color:darkgreen">*<b>IMPORTANT: </b>Landscape Orientation Only (Width of image should be more than height)*</p>')),
                ('date', models.DateField(blank=True, null=True)),
                ('authors', models.CharField(max_length=200)),
                ('journal_name', models.CharField(max_length=100)),
                ('doiLink', models.TextField()),
                ('abstract', ckeditor.fields.RichTextField()),
                ('category', models.ManyToManyField(blank=True, to='sengupta_lab.Papers_Category')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
