# Generated by Django 3.2.4 on 2021-06-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Add new category')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='student_type',
            field=models.ManyToManyField(blank=True, to='sengupta_lab.Student_Type'),
        ),
    ]
