# Generated by Django 3.2.4 on 2021-06-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0002_auto_20210619_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='student_type',
        ),
        migrations.DeleteModel(
            name='Student_Type',
        ),
    ]
