# Generated by Django 3.2.4 on 2021-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0004_auto_20210619_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Type',
            new_name='Member_Type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='student_type',
        ),
        migrations.AddField(
            model_name='team',
            name='member_type',
            field=models.ManyToManyField(blank=True, to='sengupta_lab.Member_Type'),
        ),
    ]
