# Generated by Django 3.2.4 on 2021-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0005_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='subText',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('under graduate ', 'Undergraduate '), ('masters', 'Mtech'), ('phd', 'PHD'), ('other', 'other')], default='other', max_length=25),
        ),
    ]
