# Generated by Django 3.2.4 on 2021-06-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0005_auto_20210619_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member_type',
            options={'verbose_name_plural': 'Member Type'},
        ),
    ]
