# Generated by Django 3.2.4 on 2021-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0007_software_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='tags',
        ),
        migrations.AddField(
            model_name='software',
            name='tags',
            field=models.TextField(default='none', verbose_name=[('ml', 'ML'), ('other', 'Other')]),
        ),
    ]
