# Generated by Django 3.2.4 on 2021-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0008_auto_20210608_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
