# Generated by Django 3.2.4 on 2021-06-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0009_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='tags',
        ),
        migrations.AddField(
            model_name='software',
            name='comp_bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='software',
            name='ml',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='software',
            name='single_cells',
            field=models.BooleanField(default=True),
        ),
    ]
