# Generated by Django 3.2.4 on 2021-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0010_auto_20210608_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='comp_bio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='ml',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='single_cells',
            field=models.BooleanField(default=False),
        ),
    ]
