# Generated by Django 3.2.4 on 2021-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0011_auto_20210608_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='about',
        ),
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
