# Generated by Django 3.2.4 on 2021-06-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0012_auto_20210609_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imageUrl',
            field=models.TextField(null=True),
        ),
    ]
