# Generated by Django 3.2.4 on 2021-06-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0013_alter_news_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
