# Generated by Django 3.2.4 on 2021-06-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0014_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imageUrl', models.TextField(null=True)),
                ('sub_text', models.CharField(max_length=100, null=True)),
                ('link', models.TextField()),
                ('desc', models.TextField(null=True)),
            ],
        ),
    ]
