# Generated by Django 3.2.4 on 2021-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0015_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='imageUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sub_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
