# Generated by Django 3.2.4 on 2021-06-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0017_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
