# Generated by Django 3.2.4 on 2021-06-11 07:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0027_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_address', models.CharField(max_length=255)),
                ('office_address', models.CharField(max_length=255)),
                ('lab_address', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=12)),
                ('purpose', models.TextField()),
                ('additional', djongo.models.fields.JSONField()),
            ],
        ),
    ]
