# Generated by Django 3.2.4 on 2021-06-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0028_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='additional',
        ),
    ]
