# Generated by Django 3.2.4 on 2021-06-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0029_remove_footer_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='contact_phone',
            field=models.CharField(max_length=50),
        ),
    ]
