# Generated by Django 3.2.4 on 2021-06-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0030_alter_footer_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
