# Generated by Django 3.2.4 on 2021-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0031_delete_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_title', models.CharField(max_length=255)),
                ('campus_address', models.CharField(max_length=255)),
                ('address1_title', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2_title', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3_title', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('address4_title', models.CharField(max_length=255)),
                ('address4', models.CharField(max_length=255)),
                ('address5_title', models.CharField(max_length=255)),
                ('address5', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
            ],
        ),
    ]
