# Generated by Django 3.2.4 on 2021-06-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0033_auto_20210612_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='campus_title',
        ),
    ]
