# Generated by Django 3.2.4 on 2021-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0034_remove_footer_campus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='image_1',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
