# Generated by Django 3.2.4 on 2021-06-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0037_auto_20210612_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_url4',
            field=models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='image_url5',
            field=models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_url1',
            field=models.TextField(help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_url2',
            field=models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_url3',
            field=models.TextField(blank=True, help_text='<p style="color:red">*<b>IMPORTANT </b> All the Image should be of same ratio. Use landscape orientation*</p>', null=True),
        ),
    ]
