# Generated by Django 3.2.4 on 2021-06-11 21:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0038_auto_20210612_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rich_text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='text_para',
            field=models.TextField(help_text='<p style="color:green">*<b>IMPORTANT </b> <br>To make text bold, wrap it inside this tag: &lt;b&gt; Your text &lt;/b&gt;<br>To make italicize your text, wrap your text inside &lt;i&gt; Your text &lt;/i&gt;<br>To add color to a text, wrap your text inside &lt;span style="color:#4287f5" &gt; Your text &lt;/span&gt;<br> So basically you can write HTML in it *</p>'),
        ),
    ]
