# Generated by Django 3.2.4 on 2021-06-11 21:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0039_auto_20210612_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='rich_text',
        ),
        migrations.AlterField(
            model_name='home',
            name='text_para',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
