# Generated by Django 3.2.4 on 2021-06-11 21:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0040_auto_20210612_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='image_url1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='sub_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
