# Generated by Django 3.2.4 on 2021-06-11 21:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0041_auto_20210612_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='research',
            name='publication_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
