# Generated by Django 3.2.4 on 2021-06-11 22:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0042_auto_20210612_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address1_title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address2_title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address3_title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address4_title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address5',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address5_title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='campus_address',
        ),
        migrations.AddField(
            model_name='footer',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
