# Generated by Django 3.2.4 on 2021-06-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0043_auto_20210612_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
