# Generated by Django 3.2.4 on 2021-06-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0044_rename_imageurl_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
