# Generated by Django 3.2.4 on 2021-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0046_alter_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Btech', 'Btech '), ('Mtech', 'Mtech'), ('PHD', 'PHD'), ('Other', 'other')], default='other', max_length=25),
        ),
    ]
