# Generated by Django 3.2.4 on 2021-06-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0047_alter_team_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tag Name')),
                ('color', models.CharField(max_length=10, verbose_name='Add color of the tag')),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(verbose_name='Paper title'),
        ),
    ]
