# Generated by Django 3.2.4 on 2021-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0048_auto_20210614_2314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper_Category',
            new_name='Software_Tag',
        ),
        migrations.AddField(
            model_name='software',
            name='choice',
            field=models.ManyToManyField(blank=True, to='sengupta_lab.Software_Tag'),
        ),
    ]
