# Generated by Django 3.2.4 on 2021-06-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0049_auto_20210616_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Software_Tag',
        ),
    ]
