# Generated by Django 3.2.4 on 2021-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0050_auto_20210616_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tag Name')),
                ('color', models.CharField(max_length=10, verbose_name='Add color of the tag')),
            ],
        ),
    ]
