# Generated by Django 3.2.4 on 2021-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0051_software_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sengupta_lab.Software_Tag'),
        ),
    ]
