# Generated by Django 3.2.4 on 2021-06-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0052_software_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='comp_bio',
        ),
        migrations.RemoveField(
            model_name='software',
            name='ml',
        ),
        migrations.RemoveField(
            model_name='software',
            name='single_cells',
        ),
    ]
