# Generated by Django 3.2.4 on 2021-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0053_auto_20210617_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Add new category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='category',
        ),
        migrations.AddField(
            model_name='paper',
            name='category',
            field=models.ManyToManyField(blank=True, to='sengupta_lab.Papers_Category'),
        ),
    ]
