# Generated by Django 3.2.4 on 2021-06-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0054_auto_20210619_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
    ]
