# Generated by Django 3.2.4 on 2021-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sengupta_lab', '0056_auto_20210619_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='journalLink',
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Paper Title'),
        ),
    ]
